# TWBC Database Analysis

## 1. Show table Players

In [13]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('../data/processed/twbc.db')

# Query the players table
df_players = pd.read_sql("SELECT * FROM players", conn)

# Display the results
df_players

    player_id           nick             full_name  team_id
0           1        wbc1211           Wang Siyuan       18
1           2         wbc366           Wang Haoran        1
2           3     wbc3ifndef           Jakub Horák        3
3           4           wbca          Adam Horváth        2
4           5  wbcadelstepan         Libor Krejčíř        7
5           6       wbcalleb        Alexey Lebedev       13
6           7       wbcangst     Piotr Małowiejski       12
7           8       wbcashot       Ashot Avetisyan       15
8           9         wbcasz            Gábor Nagy        9
9          10          wbcbb     Bogdan Brachaczek       11
10         11      wbcbeetle       Michał Żukowski       11
11         12      wbcbogimp         Anton Efremov       16
12         13    wbcbromozel           Ilya Katsev       13
13         14           wbcc            Petr Žižka        2
14         15      wbcciaran          Ciarán Lucey        8
15         16    wbccoldmind   Stanislav Hyžík jr.       17
16         17    wbccrosslet    Karol Podwyszyński       12
17         18       wbccsaba         Csaba Kamarás       10
18         19           wbcd      František Fňukal        2
19         20     wbcdeafbat           Jan Kopecký        6
20         21  wbcdistilfire         Petr Podolský        4
21         22     wbcfojtman          Jakub Fojtík        5
22         23       wbcfurla          Ilya Muratov       13
23         24      wbcfuzaty          Michal Holec       17
24         25         wbcg3m             Igor Eged       14
25         26     wbcgenghis            Milán Nagy       14
26         27     wbcgeordie   Stanislav Hyžík sr.       17
27         28      wbchajnal       Hajnalka Kovács       16
28         29      wbcheater       Łukasz Majksner       15
29         30        wbciron        Zoltán Sonkoly        8
30         31       wbciwbtc          Lukáš Souček        3
31         32     wbckakosik            Eva Orlova       16
32         33   wbckaktuszka     Krisztina Kamarás       10
33         34    wbckremufka      Szczepan Łukasik       15
34         35       wbclasek       Zoltán Menyhárt        9
35         36   wbclojzeidon           Alois Mikeš        4
36         37        wbcmark          Márk Horváth        8
37         38      wbcmartez         Martin Muzika        3
38         39      wbcmatiss        Matīss Riherts       15
39         40       wbcmichi     Michal Ferdinandy       14
40         41       wbcmk108         Denis Kachaev       13
41         42       wbcmulan               Bai Liu       18
42         43  wbcnguyenminh      Nguyễn Công Minh       18
43         44     wbcnirvana         Róbert Pátkai        9
44         45     wbcpangbai        Zhang Haoxiang        1
45         46    wbcpeaceman           Paweł Nowak       12
46         47     wbcperoxid        Štěpán Tesařík        4
47         48       wbcpiggi           Matěj Holub        5
48         49      wbcplayer              Li Fuwen       18
49         50     wbcpuholek           Michał Zajk       11
50         51      wbcpurkys         Jan Purkrábek        6
51         52     wbcquantum     Adrian Fitzermann       11
52         53       wbcrichi      Richard Červenka       17
53         54      wbcrostas         Ferenc Rostás        9
54         55      wbcseabow         Jana Adámková       17
55         56         wbcset  Konstantin Solomatin       16
56         57       wbcshpek        Radim Kostlivý        6
57         58       wbcsiwer     Michał Pietrusiak       12
58         59      wbcskoupy             Vít Jiřík        7
59         60   wbctasemnice         Tomáš Palacký        5
60         61       wbctorpe      M. Nándor Halena       10
61         62        wbcuida           Liu Xiangbo        1
62         63     wbcvotocek         Jakub Šalajka        7
63         64  wbcwonderwall           Josef Holba        5
64         65        wbcyu20            Liu Wenhao        1
65         66        wbczoli         Zoltán László        8

## 2. Custom

In [17]:
df_leaderboard = pd.read_sql("""
    SELECT
        RANK() OVER (ORDER BY total_score DESC, efficiency DESC) AS "Place",
        player_name AS "Player",
        player_nick AS "WBC nick",
        team AS "Team",
        total_score AS "Score",
        wins AS "Wins",
        draws AS "Draws",
        losses AS "Losses",
        PRINTF('%.1f %%', efficiency * 100) AS "Efficiency",
        total_games AS "Games"
    FROM v_player_wld
    ORDER BY "Place";
""", conn)

# Display the dataframe
df_leaderboard

,Place,Player,WBC nick,Team,Score,Wins,Draws,Losses,Efficiency,Games
0,1,Zoltán László,wbczoli,Hungary A,86.5,86,1,9,90.1 %,96.0
1,2,Igor Eged,wbcg3m,Slovakia,80.5,79,3,26,74.5 %,108.0
2,3,František Fňukal,wbcd,Czechia A,76.5,77,3,30,70.8 %,108.0
3,4,Petr Žižka,wbcc,Czechia A,76.0,77,0,32,70.4 %,108.0
4,5,Adam Horváth,wbca,Czechia A,75.5,75,1,32,69.9 %,108.0
5,6,Ilya Muratov,wbcfurla,Russia,75.0,75,0,33,69.4 %,108.0
6,7,Michał Zajk,wbcpuholek,Poland A,74.0,74,0,22,77.1 %,96.0
7,8,Michał Żukowski,wbcbeetle,Poland A,70.5,70,1,13,83.9 %,84.0
8,9,Nguyễn Công Minh,wbcnguyenminh,Team International D,69.5,69,1,26,72.4 %,96.0
9,10,Martin Muzika,wbcmartez,Czechia B,66.0,65,2,41,61.1 %,108.0
10,11,Zoltán Sonkoly,wbciron,Hungary A,65.0,64,2,30,67.7 %,96.0
11,12,Liu Wenhao,wbcyu20,China,65.0,65,0,44,60.2 %,108.0
12,13,Adrian Fitzermann,wbcquantum,Poland A,64.0,64,0,8,88.9 %,72.0
13,14,Alexey Lebedev,wbcalleb,Russia,64.0,64,0,32,66.7 %,96.0
14,15,Lukáš Souček,wbciwbtc,Czechia B,62.0,60,4,44,57.4 %,108.0
15,15,Li Fuwen,wbcplayer,Team International D,62.0,56,2,45,57.4 %,108.0
16,17,Róbert Pátkai,wbcnirvana,Hungary B,61.0,61,0,47,56.5 %,108.0
17,18,Bogdan Brachaczek,wbcbb,Poland A,60.0,60,0,12,83.3 %,72.0
18,19,Jan Kopecký,wbcdeafbat,Czechia E,57.0,57,0,51,52.8 %,108.0
19,20,Jakub Horák,wbc3ifndef,Czechia B,54.0,54,0,54,50.0 %,108.0
20,21,Matīss Riherts,wbcmatiss,Team International A,53.5,53,1,18,74.3 %,72.0
21,22,Gábor Nagy,wbcasz,Hungary B,53.5,53,1,42,55.7 %,96.0
22,23,Alois Mikeš,wbclojzeidon,Czechia C,51.5,51,1,56,47.7 %,108.0
23,24,Milán Nagy,wbcgenghis,Slovakia,50.0,49,2,57,46.3 %,108.0
24,25,Ciarán Lucey,wbcciaran,Hungary A,49.0,49,0,23,68.1 %,72.0
25,26,Zhang Haoxiang,wbcpangbai,China,47.0,47,0,25,65.3 %,72.0
26,27,Tomáš Palacký,wbctasemnice,Czechia D,46.0,46,0,50,47.9 %,96.0
27,28,Michal Ferdinandy,wbcmichi,Slovakia,46.0,46,0,62,42.6 %,108.0
28,29,Radim Kostlivý,wbcshpek,Czechia E,45.0,45,0,63,41.7 %,108.0
29,30,Liu Xiangbo,wbcuida,China,44.0,44,0,64,40.7 %,108.0
30,31,Štěpán Tesařík,wbcperoxid,Czechia C,43.0,43,0,65,39.8 %,108.0
31,32,Denis Kachaev,wbcmk108,Russia,42.5,42,1,29,59.0 %,72.0
32,33,Stanislav Hyžík jr.,wbccoldmind,Team International C,39.0,39,0,69,36.1 %,108.0
33,33,Petr Podolský,wbcdistilfire,Czechia C,39.0,39,0,69,36.1 %,108.0
34,35,Jakub Fojtík,wbcfojtman,Czechia D,38.5,37,3,56,40.1 %,96.0
35,36,Ferenc Rostás,wbcrostas,Hungary B,38.0,38,0,34,52.8 %,72.0
36,37,Konstantin Solomatin,wbcset,Team International B,37.5,37,1,34,52.1 %,72.0
37,38,Zoltán Menyhárt,wbclasek,Hungary B,37.0,37,1,11,77.1 %,48.0
38,39,Michał Pietrusiak,wbcsiwer,Poland B,37.0,37,0,35,51.4 %,72.0
39,40,Ilya Katsev,wbcbromozel,Russia,36.0,36,0,12,75.0 %,48.0
40,41,Szczepan Łukasik,wbckremufka,Team International A,35.0,35,0,25,58.3 %,60.0
41,42,Josef Holba,wbcwonderwall,Czechia D,35.0,35,0,37,48.6 %,72.0
42,43,Anton Efremov,wbcbogimp,Team International B,34.5,34,1,37,47.9 %,72.0
43,43,Jakub Šalajka,wbcvotocek,Czechia F,34.5,33,3,36,47.9 %,72.0
44,45,Ashot Avetisyan,wbcashot,Team International A,33.0,33,0,15,68.8 %,48.0
45,46,Márk Horváth,wbcmark,Hungary A,33.0,33,0,27,55.0 %,60.0
46,47,Piotr Małowiejski,wbcangst,Poland B,29.0,29,0,43,40.3 %,72.0
47,48,Stanislav Hyžík sr.,wbcgeordie,Team International C,29.0,29,0,56,34.5 %,84.0
48,49,Jan Purkrábek,wbcpurkys,Czechia E,29.0,29,0,79,26.9 %,108.0
49,50,Matěj Holub,wbcpiggi,Czechia D,24.0,24,0,36,40.0 %,60.0
50,51,Paweł Nowak,wbcpeaceman,Poland B,22.0,22,0,14,61.1 %,36.0
51,52,Libor Krejčíř,wbcadelstepan,Czechia F,21.0,21,0,51,29.2 %,72.0
52,53,Łukasz Majksner,wbcheater,Team International A,19.0,19,0,17,52.8 %,36.0
53,54,Vít Jiřík,wbcskoupy,Czechia F,14.0,14,0,41,23.3 %,60.0
54,55,Eva Orlova,wbckakosik,Team International B,13.0,14,0,35,27.1 %,48.0
55,56,Hajnalka Kovács,wbchajnal,Team International B,11.0,11,0,15,45.8 %,24.0
56,57,Wang Siyuan,wbc1211,Team International D,7.0,7,0,65,9.7 %,72.0
57,58,Karol Podwyszyński,wbccrosslet,Poland B,5.0,5,0,31,13.9 %,36.0
58,59,Richard Červenka,wbcrichi,Team International C,5.0,5,0,67,6.9 %,72.0
59,60,Jana Adámková,wbcseabow,Team International C,4.0,4,0,32,11.1 %,36.0
60,61,Csaba Kamarás,wbccsaba,Hungary C,4.0,4,0,104,3.7 %,108.0
61,61,Krisztina Kamarás,wbckaktuszka,Hungary C,4.0,4,0,104,3.7 %,108.0
62,63,M. Nándor Halena,wbctorpe,Hungary C,3.0,3,0,105,2.8 %,108.0
63,64,Michal Holec,wbcfuzaty,Team International C,1.0,1,0,23,4.2 %,24.0
64,65,Wang Haoran,wbc366,China,1.0,1,0,35,2.8 %,36.0
65,65,Bai Liu,wbcmulan,Team International D,1.0,1,1,35,2.8 %,36.0